server:
  port: 8092

spring:
  datasource:
    username: ${JDBC_LOGIN}
    password: ${JDBC_PASSWORD}
    url: ${JDBC_URL}
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        user_sql_comments: false
        temp:
          user_jdbc_metadata_default: false