spring:
  application:
    name: Zuul


# routes requests with context ../authors/
# to a registered 'author-service'
zuul:  routes:
    author-service: /authors/**    book-service: /books/**